version: '3.8'

services:
  ubuntu-ssh:
    image: ubuntu:22.04
    container_name: eryzaa-ubuntu-ssh
    hostname: eryzaa-ubuntu
    ports:
      - "2222:22"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y openssh-server sudo curl wget nano vim htop &&
        mkdir -p /var/run/sshd &&
        echo 'root:eryzaa2024' | chpasswd &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        service ssh start &&
        tail -f /dev/null
      "
    restart: unless-stopped
    networks:
      - ssh-network

networks:
  ssh-network:
    driver: bridge
